default_language_version:
  python: python3.10

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

#  - repo: local
#    hooks:
#      - id: pyupgrade
#        name: pyupgrade
#        entry: poetry run pyupgrade --py310-plus
#        types: [python]
#        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        types: [python]
        language: system
#
#repos:
#- repo: https://github.com/psf/black
#  rev: 21.5b1
#  hooks:
#  - id: black
#- repo: https://github.com/pycqa/isort
#  rev: 5.8.0
#  hooks:
#  - id: isort
#    args: ["--profile", "black", "--filter-files"]
#- repo: https://github.com/pycqa/flake8
#  rev: 3.9.2
#  hooks:
#  - id: flake8
#- repo: https://github.com/igorshubovych/markdownlint-cli
#  rev: v0.27.1
#  hooks:
#  - id: markdownlint
#- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
#  rev: 2.3.5
#  hooks:
#  - id: editorconfig-checker
