# This file contains values from Cookiecutter

default_context:
  project_name: "fluentqa-pyutils"
  project_plug: "fluentqa_pyutils"
  project_description: "Awesome `fluentqa_pyutils` is a Python cli/package "
  organization: "fluentqa"
  license: "MIT"
  minimal_python_version: 3.10
  github_name: "fluentqa"
  email: "hello@fluentqa-pyutils.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
